version: '3'

services:
  app:
    build:
      context: .
    entrypoint: sh -c "sh ./initgraphql.sh" #script inicial
    #entrypoint: sh -c "go mod tidy && go run server.go" #depois de inicializar pela primeira vez 
    container_name: mygolang 
    volumes:
      - .:/app
    tty:
      true