version: '3'

services:
  app:
    build:
      context: .
    entrypoint: sh -c "sh ./initgraphql.sh"
    container_name: mygolang
    volumes:
      - .:/app
    ports:
      - 8080:8080
    tty:
      true